#include "render/FontRenderer.hpp"
#include <glad/glad.h>
#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_SYNTHESIS_H
#include <array>
#include <algorithm>
#include <stdexcept>
#include <vector>
namespace strategy { namespace {
struct Vertex {glm::vec2 position,uv;};
std::uint32_t shader(GLenum type,const char*source){auto id=glCreateShader(type);glShaderSource(id,1,&source,nullptr);glCompileShader(id);GLint ok=0;glGetShaderiv(id,GL_COMPILE_STATUS,&ok);if(!ok){glDeleteShader(id);throw std::runtime_error("Font shader compilation failed");}return id;}
std::filesystem::path fontPath(){for(const auto& path:{std::filesystem::path{"assets/fonts/Inter-Bold.ttf"},std::filesystem::path{"C:/Windows/Fonts/segoeuib.ttf"},std::filesystem::path{"C:/Windows/Fonts/arialbd.ttf"},std::filesystem::path{"assets/fonts/Inter-Regular.ttf"},std::filesystem::path{"C:/Windows/Fonts/segoeui.ttf"},std::filesystem::path{"C:/Windows/Fonts/arial.ttf"}})if(std::filesystem::exists(path))return path;throw std::runtime_error("No UI font found; add assets/fonts/Inter-Bold.ttf");}
}
FontRenderer::FontRenderer(){FT_Library library=nullptr;FT_Face face=nullptr;if(FT_Init_FreeType(&library))throw std::runtime_error("Could not initialize FreeType");const auto path=fontPath();if(FT_New_Face(library,path.string().c_str(),0,&face)){FT_Done_FreeType(library);throw std::runtime_error("Could not load UI font: "+path.string());}FT_Set_Pixel_Sizes(face,0,48);
 constexpr int width=1024,height=512;std::vector<unsigned char>atlas(width*height,0);int penX=1,penY=1,rowHeight=0;
 for(unsigned c=32;c<128;++c){if(FT_Load_Char(face,c,FT_LOAD_RENDER))continue;FT_GlyphSlot_Embolden(face->glyph);const auto&b=face->glyph->bitmap;if(penX+int(b.width)+1>=width){penX=1;penY+=rowHeight+1;rowHeight=0;}for(unsigned row=0;row<b.rows;++row)for(unsigned column=0;column<b.width;++column)atlas[(penY+int(row))*width+penX+int(column)]=b.buffer[row*b.pitch+column];Glyph&g=glyphs_[c];g.size={b.width,b.rows};g.bearing={face->glyph->bitmap_left,face->glyph->bitmap_top};g.advance=float(face->glyph->advance.x>>6);g.uvMin={float(penX)/width,float(penY)/height};g.uvMax={float(penX+int(b.width))/width,float(penY+int(b.rows))/height};penX+=int(b.width)+1;rowHeight=std::max(rowHeight,int(b.rows));}
 FT_Done_Face(face);FT_Done_FreeType(library);glGenTextures(1,&texture_);glBindTexture(GL_TEXTURE_2D,texture_);glPixelStorei(GL_UNPACK_ALIGNMENT,1);glTexImage2D(GL_TEXTURE_2D,0,GL_R8,width,height,0,GL_RED,GL_UNSIGNED_BYTE,atlas.data());glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);
 constexpr const char*vs=R"(#version 450 core
layout(location=0)in vec2 position;layout(location=1)in vec2 uvIn;uniform vec2 offset;out vec2 uv;void main(){gl_Position=vec4(position+offset,0,1);uv=uvIn;})";
 constexpr const char*fs=R"(#version 450 core
in vec2 uv;uniform sampler2D atlas;uniform vec3 color;out vec4 outColor;void main(){float a=texture(atlas,uv).r;outColor=vec4(color,a);})";
 auto v=shader(GL_VERTEX_SHADER,vs),f=shader(GL_FRAGMENT_SHADER,fs);program_=glCreateProgram();glAttachShader(program_,v);glAttachShader(program_,f);glLinkProgram(program_);glDeleteShader(v);glDeleteShader(f);glGenVertexArrays(1,&vao_);glGenBuffers(1,&vbo_);glBindVertexArray(vao_);glBindBuffer(GL_ARRAY_BUFFER,vbo_);glEnableVertexAttribArray(0);glVertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,sizeof(Vertex),nullptr);glEnableVertexAttribArray(1);glVertexAttribPointer(1,2,GL_FLOAT,GL_FALSE,sizeof(Vertex),(void*)sizeof(glm::vec2));glBindVertexArray(0);}
FontRenderer::~FontRenderer(){glDeleteBuffers(1,&vbo_);glDeleteVertexArrays(1,&vao_);glDeleteProgram(program_);glDeleteTextures(1,&texture_);}
void FontRenderer::draw(const std::string&text,float x,float top,float pixelHeight,glm::vec3 color,int width,int height)const{const float scale=pixelHeight/48.0F;const float baseline=top+pixelHeight;std::vector<Vertex>vertices;for(unsigned char c:text){if(c>=glyphs_.size())continue;const Glyph&g=glyphs_[c];const float left=x+g.bearing.x*scale,right=left+g.size.x*scale,bottom=baseline-g.bearing.y*scale,lower=bottom+g.size.y*scale;auto ndc=[width,height](float px,float py){return glm::vec2{px/width*2-1,1-py/height*2};};vertices.insert(vertices.end(),{{ndc(left,bottom),{g.uvMin.x,g.uvMin.y}},{ndc(left,lower),{g.uvMin.x,g.uvMax.y}},{ndc(right,bottom),{g.uvMax.x,g.uvMin.y}},{ndc(right,bottom),{g.uvMax.x,g.uvMin.y}},{ndc(left,lower),{g.uvMin.x,g.uvMax.y}},{ndc(right,lower),{g.uvMax.x,g.uvMax.y}}});x+=g.advance*scale;}if(vertices.empty())return;glUseProgram(program_);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,texture_);glUniform1i(glGetUniformLocation(program_,"atlas"),0);glBindVertexArray(vao_);glBindBuffer(GL_ARRAY_BUFFER,vbo_);glBufferData(GL_ARRAY_BUFFER,GLsizeiptr(vertices.size()*sizeof(Vertex)),vertices.data(),GL_DYNAMIC_DRAW);const GLint colorLocation=glGetUniformLocation(program_,"color"),offsetLocation=glGetUniformLocation(program_,"offset");const glm::vec3 shadow{0.01F,0.015F,0.02F};glUniform3fv(colorLocation,1,&shadow.x);glUniform2f(offsetLocation,2.0F/width,-2.0F/height);glDrawArrays(GL_TRIANGLES,0,GLsizei(vertices.size()));glUniform3fv(colorLocation,1,&color.x);glUniform2f(offsetLocation,0.0F,0.0F);glDrawArrays(GL_TRIANGLES,0,GLsizei(vertices.size()));glBindVertexArray(0);}
}
